jaya/urls.py
from .import views
from django.urls import path
app_name='jaya'
urlpatterns = [
    path('abcd/',views.jayasurya,name='abcd'),
    path('jjj/',views.abhijith,name='jjj'),
    path('hhh/',views.jithu,name='hhh'),
    path('lll/',views.ajin,name='lll'),
    path('sign/',views.deva,name='sign'),
    path('log/',views.ajin,name='log'),
    path('logout/',views.vipin,name='sss'),
    path('register/',views.reg,name='rrr')
]

work4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include ('jaya.urls')),
]

jaya/models.py
from django.db import models

class Product(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    price = models.IntegerField(max_length=3)
    offer = models.BooleanField(default=False)
    dimensions = models.CharField(max_length=300,null=True,blank=True)
    image = models.ImageField(upload_to='pics')
    # def __str__(self):
    #     return self.title

jaya/views.py
from django.shortcuts import render,redirect
from .models import Product
from django.contrib.auth.models import auth
from django.contrib import messages



# Create your views here.
def jayasurya(request):
    return render(request, "jithu.html", )


def abhijith(request):
    A = Product.objects.all()
    return render(request, 'haha.html', {'ob': A})


def jithu(request):
    return render(request, "index1.html")


def ajin(request):
    if request.method == 'POST':
        a=request.POST['username']
        b=request.POST['password']
        user=auth.authenticate(username=a,password=b)
        if user is not None:
            auth.login(request,user)
            return redirect("jaya:hhh")
        else:
            messages.error(request,'invaild data')

    return render(request, "login.html")


def deva(request):
    return render(request, "sign in.html")


def ajil(request):
    return render(request, "logged.html")
def vipin(request):

    auth.logout(request)
    return redirect('jaya:hhh')

def reg(request):
    return render(request,'register.html')
    # if request.method == 'POST':
       # a = request.POST['username']
        #b = request.POST['password']
        #c = request.POST['firstname']
        #d = request.POST['lastname']
        #e = request.POST['gmail']
        #user = auth.authenticate(username=a, password=b,firstname=c,lastname=d,gmail=e)

templates/abhi.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<!--    <link rel="stylesheet" href="style.css">-->
<!--    <style>-->
<!--        h{color:blue}-->
<!--    </style>-->
</head>
<body>
    <div>
        <img src="{% static 'img/wp1869720.jpg' %}" alt="">
     <div>
         <h>
            CREATIVE
        </h>
     </div>
        <P style="    color: red;">
            Creativity is a phenomenon whereby something new and somehow valuable is formed. The created item may be intangible (such as an idea, a scientific theory, a musical composition, or a joke) or a physical object (such as an invention, a literary work, or a painting).

Scholarly interest in creativity is found in a number of disciplines, primarily psychology, business studies, and cognitive science, but also education, technology, engineering, philosophy (particularly philosophy of science), theology, sociology, linguistics, and economics, covering the relations between creativity and general intelligence, personality type, mental and neurological processes, mental health, or artificial intelligence; the potential for fostering creativity through education and training; the fostering of creativity for national economic benefit, and the application of creative resources to improve the effectiveness of teaching and learning.
        </P>
    </div>
    <div>
        <img src="{% static 'img/photography.jpeg' %}" alt="">
        <div class="heading ">
         <h style="color:red">
           PHOTOGRAPHY
        </h>
     </div>
        <P>
           Photography is the art, application and practice of creating durable images by recording light or other electromagnetic radiation, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film. It is employed in many fields of science, manufacturing (e.g., photolithography), and business, as well as its more direct uses for art, film and video production, recreational purposes, hobby, and mass communication.
        </P>
    </div>
    <div>
        <img src="{% static 'img/ps.jpg' %}" alt="">
         <div class="heading">
         <h style="font-style:italic">
           PHOTOSHOP
        </h>
        </div>
        <P>
            Adobe Photoshop is a raster graphics editor developed and published by Adobe Inc. for Windows and macOS. It was originally created in 1988 by Thomas and John Knoll. Since then, this software has become the industry standard not only in raster graphics editing, but in digital art as a whole. The software's name has thus become a generic trademark, leading to its usage as a verb (e.g. "to photoshop an image", "photoshopping", and "photoshop contest") although Adobe discourages such use.

        </P>
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}

</head>
<body>
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    {% include 'script.html' %}

</body>
</html>

templates/footer.html
<footer>
          <p>Copyright &copy; 2017 Your Company

        	| Designed by <em>TemplateMo</em></p>
        </footer>

templates/haha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%for i in ob%}
<h>{{i.title}}</h>
<p>{{i.description}}</p>
<p>{{i.price}}</p>
{%endfor%}

</body>
</html>

templates/head.html
{% load static %}
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Newline CSS Template with a video background</title>
<!--
Newline Template
http://www.templatemo.com/tm-503-newline
-->
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css'%}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css'%}">
        <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'%}"></script>
    </head>

templates/index.html
{% extends 'base.html' %}
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->

    <body>
{% block content %}
        <div class="overlay"></div>
        <section class="top-part">
          <video controls autoplay loop>
            <source src="videos/video.mp4" type="video/mp4">
            <source src="videos/video.ogg" type="video/ogg">
          Your browser does not support the video tag.
          </video>
        </section>
        
        <section class="cd-hero">

          <div class="cd-slider-nav">
            <nav>
              <span class="cd-marker item-1"></span>
              <ul>
                <li class="'selected"><a href="#0"><div class="image-icon"><img src="{% static 'img/home-icon.png'%}"></div><h6>Welcome</h6></a></li>
                   {%if user.is_authenticated%}
                       <li><a href="{% url 'jaya:sss'%}"><div class="image-icon"><img src="{% static 'img/about-icon.png' %}"></div><h6>log out</h6></a></li>
                    {%else%}
                       <li><a href="{% url 'jaya:lll'%}"><div class="image-icon"><img src="{% static 'img/about-icon.png' %}"></div><h6>log in</h6></a></li>
                   {%endif%}



                <li><a href="{%url 'jaya:sign'%}"><div class="image-icon"><img src="{% static 'img/featured-icon.png' %}"></div><h6>sign up</h6></a></li>
                <li><a href="'#0"><div class="image-icon"><img src="{% static 'img/projects-icon.png' %}"></div><h6>Projects</h6></a></li>
                <li><a href="#'0"><div class="image-icon"><img src="{% static 'img/contact-icon.png' %}"></div><h6>Contact Us</h6></a></li>'img/contact-icon.png"></div><h6>Contact Us</h6></a></li>'%}
              </ul>
            </nav>
          </div> <!-- .cd-slider-nav -->

          <ul class="cd-hero-slider">

            <li class="selected">
              <div class="heading">
                <h1>NEWLINE</h1>
                <span>Welcome To Web Design Agency</span>
              </div>
              <div class="cd-full-width first-slide">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="content first-content">
                        <h4>{{nl1.head}}</h4>
                        <p>MOB: {{nl1.phn}}{{nl1.sub}}Newline is free CSS template by TemplateMo. Credits go to <a href="https://videos.pexels.com/videos/busy-street-in-the-city-1089" target="_blank">Pexels.com</a> for a video background and <a href="http://unsplash.com" target="_blank">Unsplash</a> for images. Please tell your friends about TemplateMo and this is a way to help back. Thank you. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dictum convallis mi. In dapibus auctor dictum donec mattis quis eros ultricies feugiat.</p>
                        <div class="primary-button">
                          <a href="#">Discover More</a>
                        </div>
                      </div>
                    </div>
                  </div>                  
                </div>
              </div>
            </li>

            <li>
              <div class="heading">
                <h1>About Us</h1>
                <span>Get More Info About Our Agency</span> 
              </div>
              <div class="cd-half-width second-slide">   
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="content second-content">
                        <div class="row">
                          <div class="col-md-7 left-image">
                            <img src="{% static 'img/left-about-image.jpg' %}">
                          </div>
                          <div class="col-md-5">
                            <div class="right-about-text">
                              <h4>Who we are?</h4>
                              <p>Fusce neque leo, dapibus sed imperdiet sed, vulputate sed purus. Nam eget justo in nibh facilisis rhoncus. Donec et risus non mauris lobortis convallis. Aliquam id urna quis ante blandit semper.</p>
                              <div class="primary-button">
                                <a href="#">Discover More</a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-7">
                            <div class="left-about-text">
                              <h4>What we do?</h4>
                              <p>Nam aliquam ultrices interdum. Vivamus metus mi, accumsan a tincidunt a, efficitur id felis. Vivamus non nibh malesuada, vestibulum nulla in, iaculis sem. Aenean tincidunt faucibus ipsum, ac aliquet nunc accumsan sed. Nulla sodales nunc sit amet libero egestas, ut interdum ex congue.</p>
                              <div class="primary-button">
                                <a href="#">Discover More</a>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-5 right-image">
                            <img src="{% static 'img/right-about-image.jpg' %}">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>                  
                </div>
              </div>
            </li>

            <li>
              <div class="heading">
                <h1>Featured</h1>
                <span>We produce featured product every week</span> 
              </div>
              <div class="cd-half-width third-slide">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="content third-content">
                        <div class="row">
                          <div class="col-md-7 left-image">
                            <img src="{% static 'img/left-feature-image.png' %}">
                          </div>
                          <div class="col-md-5">
                            <div class="right-feature-text">
                              <h4>Featured Product: <em>Newline</em></h4>
                              <p>Lorem ipsum dolor amet, consecte adipiscing elit, quisque dictum convallis mi. In dapibus auctor dictum donec mattis quis eros ultricies feugiat. Morbi congue faucibus mi, ague blandit curabitur ac lacinia.</p>
                              <div class="feature-list">
                                <ul>
                                  <p>- Suspendisse mattis finibus sem</p>
                                  <p>- Pellentesque et urna vel lectus</p>
                                  <p>- Vestibulum iaculis nisi dui</p>
                                  <p>- Donec sagittis eros , ac tempus ligula</p>
                                  <p>- Integer sapien risus, auctor</p>
                                </ul>
                              </div>
                              <div class="primary-button">
                                <a href="#">Discover More</a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>                  
                </div>
              </div>
            </li>

            <li>
              <div class="heading">
                <h1>Our projects</h1>
                <span>Here you can check our recent projects</span> 
              </div>
              <div class="cd-half-width fourth-slide">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="content fourth-content">
                        <div class="row">
                          <div class="col-md-3 project-item">
                            <a href="{%static 'img/item-01.jpg'%}" data-lightbox="image-1"><img src="{%static 'img/project-item-01.jpg'%}"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="{%static 'img/item-02.jpg'%}" data-lightbox="image-1"><img src="{%static 'img/project-item-02.jpg'%}"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="{%static 'img/item-03.jpg'%}" data-lightbox="image-1"><img src="{%static 'img/project-item-03.jpg'%}"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="img/item-04.jpg" data-lightbox="image-1"><img src="{%img/project-item-04.jpg"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="img/item-05.jpg" data-lightbox="image-1"><img src="img/project-item-05.jpg"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="img/item-06.jpg" data-lightbox="image-1"><img src="img/project-item-06.jpg"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="img/item-07.jpg" data-lightbox="image-1"><img src="img/project-item-07.jpg"></a>
                          </div>
                          <div class="col-md-3 project-item">
                            <a href="img/item-08.jpg" data-lightbox="image-1"><img src="img/project-item-08.jpg"></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>                  
                </div>
              </div>
            </li>

            <li>
              <div class="heading">
                <h1>Contact us</h1>
                <span>You'll be responded within 48 hrs</span> 
              </div>
              <div class="cd-half-width fivth-slide">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="content fivth-content">
                        <div class="row">
                          <div class="col-md-4">
                            <div class="left-info">
                              <p>Maecenas imperdiet sagittis lacus, ut consequat velit iaculis id. Praesent eu consequat urna. Morbi justo dolor, ornare sed lorem et, auctor iaculis ligula.
                              <br><br>
                              <em>3344 Donec mollis libero<br>at metus luctus 10110</em>
                              </p>
                              <ul class="social-icons">
                                <i><a href="#"><i class="fa fa-facebook"></i></a></i>
                                <i><a href="#"><i class="fa fa-twitter"></i></a></i>
                                <i><a href="#"><i class="fa fa-linkedin"></i></a></i>
                                <i><a href="#"><i class="fa fa-rss"></i></a></i>
                                <i><a href="#"><i class="fa fa-behance"></i></a></i>
                              </ul>
                            </div>
                          </div>
                          <div class="col-md-8">
                            <div class="row">
                              <form id="contact" action="" method="post">
                                <div class="col-md-6">
                                  <fieldset>
                                    <input name="name" type="text" class="form-control" id="name" placeholder="Your Name" required>
                                  </fieldset>
                                </div>
                                <div class="col-md-6">
                                  <fieldset>
                                    <input name="email" type="email" class="form-control" id="email" placeholder="Email" required>
                                  </fieldset>
                                </div>
                                <div class="col-md-12">
                                  <fieldset>
                                    <textarea name="message" rows="6" class="form-control" id="message" placeholder="Message" required></textarea>
                                  </fieldset>
                                </div>
                                <div class="col-md-12">
                                  <fieldset>
                                    <button type="submit" id="form-submit" class="btn">Send Message</button>
                                  </fieldset>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>                  
                </div>
              </div>
            </li>
          </ul> <!-- .cd-hero-slider -->
        </section> <!-- .cd-hero -->



    

        {% endblock content %}
    </body>

templates/jithu.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <style>img{width:100%;
    height:100%;}
body
</style>
</head>
<body>

  <div class="continer">

       <div class="row">
           <div class="co-sm-12">
               <br>
               <br>
               <h style="padding-left: 570px">
                   PHOTOHRAPHY
               </h>
               <br>
               <br>

           </div>

           <div class="col-sm-12">
               <div class="col-sm-4">
                   <img src="{%static 'img/item-01.jpg'%}" class="center">

                   
               </div>
               <div class="col-sm-4">
                   <img src=" {%static 'img/item-02.jpg'%}">
                   
               </div>
               <div class="col-sm-4">
                   <img  src="{%static 'img/lioness.jpg'%}">
                   
               </div>
           </div>
           <div class="col-sm-12">
               <div class="col-sm-4">
                   <h><center>MOBILE PHOTOGRAPHY</center></h>
                   <P><center> Taking pictures with a mobile phone. The camera technology on smartphones is more than adequate for taking photos and publishing them online. Depending on the camera quality and number of pixels, photos can be printed 8x10" and higher with excellent results.</center></P>
               </div>
               <div class="col-sm-4">
                   <h><center>NATURE PHOTOGRAPHY</center></h>
                   <p>
                       <center>
                       Nature photography is a wide range of photography taken outdoors and devoted to displaying natural elements such as landscapes, wildlife, plants, and close-ups of natural scenes and textures.
                       </center>
                   </p>
               </div>
               <div class="col-sm-4">
                   <h><center>WILDLIFE PHOTOGRAPHY</center></h>
                   <p><center>Wildlife photography is a genre of photography concerned with documenting various forms of wildlife in their natural habitat. As well as requiring photography skills, wildlife photographers may need field craft skills</center></p>
               </div>
           </div>
        
       </div>
  </div>

</body>
</html>

templates/logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>WELCOME TO DJANGO</h1>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style></style>
    <form action="." method="post">
        {%csrf_token%}


    username:<input type="text" name="username"><br>
    password:<input type="text" name="password"><br>
        <input type="submit" value="login">
</form>
</head>
<body>
     <u1>
        <li><a href="{% url 'jaya:log'%}"><div><img src=""></div><h6>login</h6></a></li>
     </u1>

</body>
</html>
{%for m in messages %}
    {{m}}
{% endfor %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
    <form action="." method="post">
        {%csrf_token%}
     username:<input type="text" name="username"><br>
     password:<input type="text" name="password"><br>
     Firstname:<input type="text" name="firstname"><br>
     Lastname:<input type="text" name="lastnamw"><br>
     gmail:<input type="text" name="gmail"><br>
        <input type="submit" value="Register">
</head>
<body>

</body>
</html>

templates/script.html
 <script src="{%static '//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'%}"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js'%}"></script>
        <script src="{%static 'js/plugins.js'%}"></script>
        <script src="{%static 'js/main.js'%}"></script>

templates/sign in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h>you are now signed in</h>

</body>
</html>